name: .NET

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:

jobs:
  build-linux:
    runs-on: ubuntu-latest

    steps:
    - name: clone repo
      uses: actions/checkout@v2
        
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 7.0.x

    - name: Restore dependencies
      run: dotnet restore

    - name: Linux build
      run: |
        cd StlSpy
        dotnet publish -o Linux -r linux-x64 --self-contained -p:PublishSingleFile=true -p:Configuration=Release
        chmod a+x Linux/StlSpy

    - name: Zip Linux Build
      uses: edgarrc/action-7z@v1
      with:
        args: 7z a Linux.7z ./StlSpy/Linux

    - name: Upload Linux artifacts
      uses: actions/upload-artifact@v2
      with:
        name: StlSpy Linux
        path: |
          Linux.7z

  build-windows:
    runs-on: windows-latest

    steps:
    - name: clone repo
      uses: actions/checkout@v2
        
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 7.0.x

    - name: Restore dependencies
      run: dotnet restore
    
    - name: Windows build
      run: |
        cd StlSpy
        dotnet publish -o Windows -r win-x64 --self-contained -p:PublishSingleFile=true -p:Configuration=Release
        
    - name: Zip Windows Build
      run: |
        Compress-Archive ./StlSpy/Windows Windows.zip

    - name: Upload Windows artifacts
      uses: actions/upload-artifact@v2
      with:
        name: StlSpy Windows
        path: |
          Windows.zip